#Makefile

all : 
	chmod 755 *
	chmod 755 ../*

profile.cgi : profile.c
	gcc -g -o profile.cgi profile.c

login.cgi : login.c
	gcc -g -o login.cgi login.c

register.cgi : register.c
	gcc -g -o register.cgi register.c

seefriends.cgi : seefriends.c
	gcc -g -o seefriends.cgi seefriends.c


